### PR TITLE
Re-enable support for typographic apostrophe.

### PR DESCRIPTION
**Pull request by rfk**
This includes some additional tests to ensure that it is correctly handled by the underlying spellcheck engine.

### CODE REVIEW

**Comment by timgraham** [comment]
This doesn't seem to resolve the spelling errors in Django.

**Comment by rfk** [comment]
> This doesn't seem to resolve the spelling errors in Django.

@timgraham to be clear, do you mean this PR has the some problem as the 1.6.9 release, or that the 1.6.10 release with things backed out didn't fix the build errors?

**Comment by timgraham** [comment]
The former. No errors with 1.6.10.

**Comment by rfk** [comment]
Phew :-)

**Pull request closed without merging**
